// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/maps.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_maps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type Step struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instruction   string                 `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	Distance      string                 `protobuf:"bytes,2,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_proto_maps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{1}
}

func (x *Step) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *Step) GetDistance() string {
	if x != nil {
		return x.Distance
	}
	return ""
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distance      string                 `protobuf:"bytes,1,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration      string                 `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Polyline      string                 `protobuf:"bytes,3,opt,name=polyline,proto3" json:"polyline,omitempty"`
	Steps         []*Step                `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_proto_maps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{2}
}

func (x *Route) GetDistance() string {
	if x != nil {
		return x.Distance
	}
	return ""
}

func (x *Route) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Route) GetPolyline() string {
	if x != nil {
		return x.Polyline
	}
	return ""
}

func (x *Route) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

type Place struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Location      *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Rating        float64                `protobuf:"fixed64,4,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Place) Reset() {
	*x = Place{}
	mi := &file_proto_maps_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Place) ProtoMessage() {}

func (x *Place) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Place.ProtoReflect.Descriptor instead.
func (*Place) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{3}
}

func (x *Place) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Place) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Place) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Place) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type GeocodeResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FormattedAddress string                 `protobuf:"bytes,1,opt,name=formatted_address,json=formattedAddress,proto3" json:"formatted_address,omitempty"`
	Location         *Location              `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GeocodeResult) Reset() {
	*x = GeocodeResult{}
	mi := &file_proto_maps_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeResult) ProtoMessage() {}

func (x *GeocodeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeResult.ProtoReflect.Descriptor instead.
func (*GeocodeResult) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{4}
}

func (x *GeocodeResult) GetFormattedAddress() string {
	if x != nil {
		return x.FormattedAddress
	}
	return ""
}

func (x *GeocodeResult) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type DistanceElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distance      string                 `protobuf:"bytes,1,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration      string                 `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistanceElement) Reset() {
	*x = DistanceElement{}
	mi := &file_proto_maps_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistanceElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistanceElement) ProtoMessage() {}

func (x *DistanceElement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistanceElement.ProtoReflect.Descriptor instead.
func (*DistanceElement) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{5}
}

func (x *DistanceElement) GetDistance() string {
	if x != nil {
		return x.Distance
	}
	return ""
}

func (x *DistanceElement) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

type DistanceRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*DistanceElement     `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistanceRow) Reset() {
	*x = DistanceRow{}
	mi := &file_proto_maps_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistanceRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistanceRow) ProtoMessage() {}

func (x *DistanceRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistanceRow.ProtoReflect.Descriptor instead.
func (*DistanceRow) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{6}
}

func (x *DistanceRow) GetElements() []*DistanceElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

type OptimizedRoute struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OptimizedOrder []int32                `protobuf:"varint,1,rep,packed,name=optimized_order,json=optimizedOrder,proto3" json:"optimized_order,omitempty"`
	TotalDistance  string                 `protobuf:"bytes,2,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`
	TotalDuration  string                 `protobuf:"bytes,3,opt,name=total_duration,json=totalDuration,proto3" json:"total_duration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OptimizedRoute) Reset() {
	*x = OptimizedRoute{}
	mi := &file_proto_maps_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizedRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizedRoute) ProtoMessage() {}

func (x *OptimizedRoute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizedRoute.ProtoReflect.Descriptor instead.
func (*OptimizedRoute) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{7}
}

func (x *OptimizedRoute) GetOptimizedOrder() []int32 {
	if x != nil {
		return x.OptimizedOrder
	}
	return nil
}

func (x *OptimizedRoute) GetTotalDistance() string {
	if x != nil {
		return x.TotalDistance
	}
	return ""
}

func (x *OptimizedRoute) GetTotalDuration() string {
	if x != nil {
		return x.TotalDuration
	}
	return ""
}

type StaticMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaticMap) Reset() {
	*x = StaticMap{}
	mi := &file_proto_maps_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticMap) ProtoMessage() {}

func (x *StaticMap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticMap.ProtoReflect.Descriptor instead.
func (*StaticMap) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{8}
}

func (x *StaticMap) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetDirectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        *Location              `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   *Location              `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectionsRequest) Reset() {
	*x = GetDirectionsRequest{}
	mi := &file_proto_maps_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectionsRequest) ProtoMessage() {}

func (x *GetDirectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectionsRequest.ProtoReflect.Descriptor instead.
func (*GetDirectionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{9}
}

func (x *GetDirectionsRequest) GetOrigin() *Location {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *GetDirectionsRequest) GetDestination() *Location {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *GetDirectionsRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type SearchPlacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Location      *Location              `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Radius        int32                  `protobuf:"varint,3,opt,name=radius,proto3" json:"radius,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPlacesRequest) Reset() {
	*x = SearchPlacesRequest{}
	mi := &file_proto_maps_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPlacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPlacesRequest) ProtoMessage() {}

func (x *SearchPlacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPlacesRequest.ProtoReflect.Descriptor instead.
func (*SearchPlacesRequest) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{10}
}

func (x *SearchPlacesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchPlacesRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *SearchPlacesRequest) GetRadius() int32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *SearchPlacesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SearchPlacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Place               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPlacesResponse) Reset() {
	*x = SearchPlacesResponse{}
	mi := &file_proto_maps_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPlacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPlacesResponse) ProtoMessage() {}

func (x *SearchPlacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPlacesResponse.ProtoReflect.Descriptor instead.
func (*SearchPlacesResponse) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{11}
}

func (x *SearchPlacesResponse) GetResults() []*Place {
	if x != nil {
		return x.Results
	}
	return nil
}

type GeocodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeocodeRequest) Reset() {
	*x = GeocodeRequest{}
	mi := &file_proto_maps_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeRequest) ProtoMessage() {}

func (x *GeocodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeRequest.ProtoReflect.Descriptor instead.
func (*GeocodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{12}
}

func (x *GeocodeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GeocodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*GeocodeResult       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeocodeResponse) Reset() {
	*x = GeocodeResponse{}
	mi := &file_proto_maps_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeResponse) ProtoMessage() {}

func (x *GeocodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeResponse.ProtoReflect.Descriptor instead.
func (*GeocodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{13}
}

func (x *GeocodeResponse) GetResults() []*GeocodeResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReverseGeocodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseGeocodeRequest) Reset() {
	*x = ReverseGeocodeRequest{}
	mi := &file_proto_maps_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseGeocodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseGeocodeRequest) ProtoMessage() {}

func (x *ReverseGeocodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseGeocodeRequest.ProtoReflect.Descriptor instead.
func (*ReverseGeocodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{14}
}

func (x *ReverseGeocodeRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type ReverseGeocodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseGeocodeResponse) Reset() {
	*x = ReverseGeocodeResponse{}
	mi := &file_proto_maps_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseGeocodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseGeocodeResponse) ProtoMessage() {}

func (x *ReverseGeocodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseGeocodeResponse.ProtoReflect.Descriptor instead.
func (*ReverseGeocodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{15}
}

func (x *ReverseGeocodeResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DistanceMatrixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origins       []*Location            `protobuf:"bytes,1,rep,name=origins,proto3" json:"origins,omitempty"`
	Destinations  []*Location            `protobuf:"bytes,2,rep,name=destinations,proto3" json:"destinations,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistanceMatrixRequest) Reset() {
	*x = DistanceMatrixRequest{}
	mi := &file_proto_maps_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistanceMatrixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistanceMatrixRequest) ProtoMessage() {}

func (x *DistanceMatrixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistanceMatrixRequest.ProtoReflect.Descriptor instead.
func (*DistanceMatrixRequest) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{16}
}

func (x *DistanceMatrixRequest) GetOrigins() []*Location {
	if x != nil {
		return x.Origins
	}
	return nil
}

func (x *DistanceMatrixRequest) GetDestinations() []*Location {
	if x != nil {
		return x.Destinations
	}
	return nil
}

func (x *DistanceMatrixRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type DistanceMatrixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*DistanceRow         `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistanceMatrixResponse) Reset() {
	*x = DistanceMatrixResponse{}
	mi := &file_proto_maps_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistanceMatrixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistanceMatrixResponse) ProtoMessage() {}

func (x *DistanceMatrixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistanceMatrixResponse.ProtoReflect.Descriptor instead.
func (*DistanceMatrixResponse) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{17}
}

func (x *DistanceMatrixResponse) GetRows() []*DistanceRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type OptimizeRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stops         []*Location            `protobuf:"bytes,1,rep,name=stops,proto3" json:"stops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeRouteRequest) Reset() {
	*x = OptimizeRouteRequest{}
	mi := &file_proto_maps_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeRouteRequest) ProtoMessage() {}

func (x *OptimizeRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeRouteRequest.ProtoReflect.Descriptor instead.
func (*OptimizeRouteRequest) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{18}
}

func (x *OptimizeRouteRequest) GetStops() []*Location {
	if x != nil {
		return x.Stops
	}
	return nil
}

type TrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackRequest) Reset() {
	*x = TrackRequest{}
	mi := &file_proto_maps_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackRequest) ProtoMessage() {}

func (x *TrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackRequest.ProtoReflect.Descriptor instead.
func (*TrackRequest) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{19}
}

type TrackLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackLocation) Reset() {
	*x = TrackLocation{}
	mi := &file_proto_maps_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackLocation) ProtoMessage() {}

func (x *TrackLocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackLocation.ProtoReflect.Descriptor instead.
func (*TrackLocation) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{20}
}

func (x *TrackLocation) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *TrackLocation) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type StaticMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Center        *Location              `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	Zoom          int32                  `protobuf:"varint,2,opt,name=zoom,proto3" json:"zoom,omitempty"`
	Size          string                 `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaticMapRequest) Reset() {
	*x = StaticMapRequest{}
	mi := &file_proto_maps_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticMapRequest) ProtoMessage() {}

func (x *StaticMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticMapRequest.ProtoReflect.Descriptor instead.
func (*StaticMapRequest) Descriptor() ([]byte, []int) {
	return file_proto_maps_proto_rawDescGZIP(), []int{21}
}

func (x *StaticMapRequest) GetCenter() *Location {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *StaticMapRequest) GetZoom() int32 {
	if x != nil {
		return x.Zoom
	}
	return 0
}

func (x *StaticMapRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

var File_proto_maps_proto protoreflect.FileDescriptor

const file_proto_maps_proto_rawDesc = "" +
	"\n" +
	"\x10proto/maps.proto\x12\x04maps\".\n" +
	"\bLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\"D\n" +
	"\x04Step\x12 \n" +
	"\vinstruction\x18\x01 \x01(\tR\vinstruction\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\tR\bdistance\"}\n" +
	"\x05Route\x12\x1a\n" +
	"\bdistance\x18\x01 \x01(\tR\bdistance\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\tR\bduration\x12\x1a\n" +
	"\bpolyline\x18\x03 \x01(\tR\bpolyline\x12 \n" +
	"\x05steps\x18\x04 \x03(\v2\n" +
	".maps.StepR\x05steps\"y\n" +
	"\x05Place\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12*\n" +
	"\blocation\x18\x03 \x01(\v2\x0e.maps.LocationR\blocation\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x01R\x06rating\"h\n" +
	"\rGeocodeResult\x12+\n" +
	"\x11formatted_address\x18\x01 \x01(\tR\x10formattedAddress\x12*\n" +
	"\blocation\x18\x02 \x01(\v2\x0e.maps.LocationR\blocation\"I\n" +
	"\x0fDistanceElement\x12\x1a\n" +
	"\bdistance\x18\x01 \x01(\tR\bdistance\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\tR\bduration\"@\n" +
	"\vDistanceRow\x121\n" +
	"\belements\x18\x01 \x03(\v2\x15.maps.DistanceElementR\belements\"\x87\x01\n" +
	"\x0eOptimizedRoute\x12'\n" +
	"\x0foptimized_order\x18\x01 \x03(\x05R\x0eoptimizedOrder\x12%\n" +
	"\x0etotal_distance\x18\x02 \x01(\tR\rtotalDistance\x12%\n" +
	"\x0etotal_duration\x18\x03 \x01(\tR\rtotalDuration\"\x1d\n" +
	"\tStaticMap\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x84\x01\n" +
	"\x14GetDirectionsRequest\x12&\n" +
	"\x06origin\x18\x01 \x01(\v2\x0e.maps.LocationR\x06origin\x120\n" +
	"\vdestination\x18\x02 \x01(\v2\x0e.maps.LocationR\vdestination\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\"\x83\x01\n" +
	"\x13SearchPlacesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12*\n" +
	"\blocation\x18\x02 \x01(\v2\x0e.maps.LocationR\blocation\x12\x16\n" +
	"\x06radius\x18\x03 \x01(\x05R\x06radius\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"=\n" +
	"\x14SearchPlacesResponse\x12%\n" +
	"\aresults\x18\x01 \x03(\v2\v.maps.PlaceR\aresults\"*\n" +
	"\x0eGeocodeRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"@\n" +
	"\x0fGeocodeResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.maps.GeocodeResultR\aresults\"C\n" +
	"\x15ReverseGeocodeRequest\x12*\n" +
	"\blocation\x18\x01 \x01(\v2\x0e.maps.LocationR\blocation\"2\n" +
	"\x16ReverseGeocodeResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x89\x01\n" +
	"\x15DistanceMatrixRequest\x12(\n" +
	"\aorigins\x18\x01 \x03(\v2\x0e.maps.LocationR\aorigins\x122\n" +
	"\fdestinations\x18\x02 \x03(\v2\x0e.maps.LocationR\fdestinations\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\"?\n" +
	"\x16DistanceMatrixResponse\x12%\n" +
	"\x04rows\x18\x01 \x03(\v2\x11.maps.DistanceRowR\x04rows\"<\n" +
	"\x14OptimizeRouteRequest\x12$\n" +
	"\x05stops\x18\x01 \x03(\v2\x0e.maps.LocationR\x05stops\"\x0e\n" +
	"\fTrackRequest\"Y\n" +
	"\rTrackLocation\x12*\n" +
	"\blocation\x18\x01 \x01(\v2\x0e.maps.LocationR\blocation\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\"b\n" +
	"\x10StaticMapRequest\x12&\n" +
	"\x06center\x18\x01 \x01(\v2\x0e.maps.LocationR\x06center\x12\x12\n" +
	"\x04zoom\x18\x02 \x01(\x05R\x04zoom\x12\x12\n" +
	"\x04size\x18\x03 \x01(\tR\x04size2\x90\x04\n" +
	"\vMapsService\x128\n" +
	"\rGetDirections\x12\x1a.maps.GetDirectionsRequest\x1a\v.maps.Route\x12E\n" +
	"\fSearchPlaces\x12\x19.maps.SearchPlacesRequest\x1a\x1a.maps.SearchPlacesResponse\x126\n" +
	"\aGeocode\x12\x14.maps.GeocodeRequest\x1a\x15.maps.GeocodeResponse\x12K\n" +
	"\x0eReverseGeocode\x12\x1b.maps.ReverseGeocodeRequest\x1a\x1c.maps.ReverseGeocodeResponse\x12K\n" +
	"\x0eDistanceMatrix\x12\x1b.maps.DistanceMatrixRequest\x1a\x1c.maps.DistanceMatrixResponse\x12A\n" +
	"\rOptimizeRoute\x12\x1a.maps.OptimizeRouteRequest\x1a\x14.maps.OptimizedRoute\x122\n" +
	"\x05Track\x12\x12.maps.TrackRequest\x1a\x13.maps.TrackLocation0\x01\x127\n" +
	"\fGetStaticMap\x12\x16.maps.StaticMapRequest\x1a\x0f.maps.StaticMapB/Z-github.com/nerdgarten/mock-maps/service/protob\x06proto3"

var (
	file_proto_maps_proto_rawDescOnce sync.Once
	file_proto_maps_proto_rawDescData []byte
)

func file_proto_maps_proto_rawDescGZIP() []byte {
	file_proto_maps_proto_rawDescOnce.Do(func() {
		file_proto_maps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_maps_proto_rawDesc), len(file_proto_maps_proto_rawDesc)))
	})
	return file_proto_maps_proto_rawDescData
}

var file_proto_maps_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_maps_proto_goTypes = []any{
	(*Location)(nil),               // 0: maps.Location
	(*Step)(nil),                   // 1: maps.Step
	(*Route)(nil),                  // 2: maps.Route
	(*Place)(nil),                  // 3: maps.Place
	(*GeocodeResult)(nil),          // 4: maps.GeocodeResult
	(*DistanceElement)(nil),        // 5: maps.DistanceElement
	(*DistanceRow)(nil),            // 6: maps.DistanceRow
	(*OptimizedRoute)(nil),         // 7: maps.OptimizedRoute
	(*StaticMap)(nil),              // 8: maps.StaticMap
	(*GetDirectionsRequest)(nil),   // 9: maps.GetDirectionsRequest
	(*SearchPlacesRequest)(nil),    // 10: maps.SearchPlacesRequest
	(*SearchPlacesResponse)(nil),   // 11: maps.SearchPlacesResponse
	(*GeocodeRequest)(nil),         // 12: maps.GeocodeRequest
	(*GeocodeResponse)(nil),        // 13: maps.GeocodeResponse
	(*ReverseGeocodeRequest)(nil),  // 14: maps.ReverseGeocodeRequest
	(*ReverseGeocodeResponse)(nil), // 15: maps.ReverseGeocodeResponse
	(*DistanceMatrixRequest)(nil),  // 16: maps.DistanceMatrixRequest
	(*DistanceMatrixResponse)(nil), // 17: maps.DistanceMatrixResponse
	(*OptimizeRouteRequest)(nil),   // 18: maps.OptimizeRouteRequest
	(*TrackRequest)(nil),           // 19: maps.TrackRequest
	(*TrackLocation)(nil),          // 20: maps.TrackLocation
	(*StaticMapRequest)(nil),       // 21: maps.StaticMapRequest
}
var file_proto_maps_proto_depIdxs = []int32{
	1,  // 0: maps.Route.steps:type_name -> maps.Step
	0,  // 1: maps.Place.location:type_name -> maps.Location
	0,  // 2: maps.GeocodeResult.location:type_name -> maps.Location
	5,  // 3: maps.DistanceRow.elements:type_name -> maps.DistanceElement
	0,  // 4: maps.GetDirectionsRequest.origin:type_name -> maps.Location
	0,  // 5: maps.GetDirectionsRequest.destination:type_name -> maps.Location
	0,  // 6: maps.SearchPlacesRequest.location:type_name -> maps.Location
	3,  // 7: maps.SearchPlacesResponse.results:type_name -> maps.Place
	4,  // 8: maps.GeocodeResponse.results:type_name -> maps.GeocodeResult
	0,  // 9: maps.ReverseGeocodeRequest.location:type_name -> maps.Location
	0,  // 10: maps.DistanceMatrixRequest.origins:type_name -> maps.Location
	0,  // 11: maps.DistanceMatrixRequest.destinations:type_name -> maps.Location
	6,  // 12: maps.DistanceMatrixResponse.rows:type_name -> maps.DistanceRow
	0,  // 13: maps.OptimizeRouteRequest.stops:type_name -> maps.Location
	0,  // 14: maps.TrackLocation.location:type_name -> maps.Location
	0,  // 15: maps.StaticMapRequest.center:type_name -> maps.Location
	9,  // 16: maps.MapsService.GetDirections:input_type -> maps.GetDirectionsRequest
	10, // 17: maps.MapsService.SearchPlaces:input_type -> maps.SearchPlacesRequest
	12, // 18: maps.MapsService.Geocode:input_type -> maps.GeocodeRequest
	14, // 19: maps.MapsService.ReverseGeocode:input_type -> maps.ReverseGeocodeRequest
	16, // 20: maps.MapsService.DistanceMatrix:input_type -> maps.DistanceMatrixRequest
	18, // 21: maps.MapsService.OptimizeRoute:input_type -> maps.OptimizeRouteRequest
	19, // 22: maps.MapsService.Track:input_type -> maps.TrackRequest
	21, // 23: maps.MapsService.GetStaticMap:input_type -> maps.StaticMapRequest
	2,  // 24: maps.MapsService.GetDirections:output_type -> maps.Route
	11, // 25: maps.MapsService.SearchPlaces:output_type -> maps.SearchPlacesResponse
	13, // 26: maps.MapsService.Geocode:output_type -> maps.GeocodeResponse
	15, // 27: maps.MapsService.ReverseGeocode:output_type -> maps.ReverseGeocodeResponse
	17, // 28: maps.MapsService.DistanceMatrix:output_type -> maps.DistanceMatrixResponse
	7,  // 29: maps.MapsService.OptimizeRoute:output_type -> maps.OptimizedRoute
	20, // 30: maps.MapsService.Track:output_type -> maps.TrackLocation
	8,  // 31: maps.MapsService.GetStaticMap:output_type -> maps.StaticMap
	24, // [24:32] is the sub-list for method output_type
	16, // [16:24] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_maps_proto_init() }
func file_proto_maps_proto_init() {
	if File_proto_maps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_maps_proto_rawDesc), len(file_proto_maps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_maps_proto_goTypes,
		DependencyIndexes: file_proto_maps_proto_depIdxs,
		MessageInfos:      file_proto_maps_proto_msgTypes,
	}.Build()
	File_proto_maps_proto = out.File
	file_proto_maps_proto_goTypes = nil
	file_proto_maps_proto_depIdxs = nil
}
