// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/maps.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MapsService_GetDirections_FullMethodName  = "/maps.MapsService/GetDirections"
	MapsService_SearchPlaces_FullMethodName   = "/maps.MapsService/SearchPlaces"
	MapsService_Geocode_FullMethodName        = "/maps.MapsService/Geocode"
	MapsService_ReverseGeocode_FullMethodName = "/maps.MapsService/ReverseGeocode"
	MapsService_DistanceMatrix_FullMethodName = "/maps.MapsService/DistanceMatrix"
	MapsService_OptimizeRoute_FullMethodName  = "/maps.MapsService/OptimizeRoute"
	MapsService_Track_FullMethodName          = "/maps.MapsService/Track"
	MapsService_GetStaticMap_FullMethodName   = "/maps.MapsService/GetStaticMap"
)

// MapsServiceClient is the client API for MapsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MapsServiceClient interface {
	GetDirections(ctx context.Context, in *GetDirectionsRequest, opts ...grpc.CallOption) (*Route, error)
	SearchPlaces(ctx context.Context, in *SearchPlacesRequest, opts ...grpc.CallOption) (*SearchPlacesResponse, error)
	Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*GeocodeResponse, error)
	ReverseGeocode(ctx context.Context, in *ReverseGeocodeRequest, opts ...grpc.CallOption) (*ReverseGeocodeResponse, error)
	DistanceMatrix(ctx context.Context, in *DistanceMatrixRequest, opts ...grpc.CallOption) (*DistanceMatrixResponse, error)
	OptimizeRoute(ctx context.Context, in *OptimizeRouteRequest, opts ...grpc.CallOption) (*OptimizedRoute, error)
	Track(ctx context.Context, in *TrackRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrackLocation], error)
	GetStaticMap(ctx context.Context, in *StaticMapRequest, opts ...grpc.CallOption) (*StaticMap, error)
}

type mapsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMapsServiceClient(cc grpc.ClientConnInterface) MapsServiceClient {
	return &mapsServiceClient{cc}
}

func (c *mapsServiceClient) GetDirections(ctx context.Context, in *GetDirectionsRequest, opts ...grpc.CallOption) (*Route, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Route)
	err := c.cc.Invoke(ctx, MapsService_GetDirections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapsServiceClient) SearchPlaces(ctx context.Context, in *SearchPlacesRequest, opts ...grpc.CallOption) (*SearchPlacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchPlacesResponse)
	err := c.cc.Invoke(ctx, MapsService_SearchPlaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapsServiceClient) Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*GeocodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeocodeResponse)
	err := c.cc.Invoke(ctx, MapsService_Geocode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapsServiceClient) ReverseGeocode(ctx context.Context, in *ReverseGeocodeRequest, opts ...grpc.CallOption) (*ReverseGeocodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReverseGeocodeResponse)
	err := c.cc.Invoke(ctx, MapsService_ReverseGeocode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapsServiceClient) DistanceMatrix(ctx context.Context, in *DistanceMatrixRequest, opts ...grpc.CallOption) (*DistanceMatrixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DistanceMatrixResponse)
	err := c.cc.Invoke(ctx, MapsService_DistanceMatrix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapsServiceClient) OptimizeRoute(ctx context.Context, in *OptimizeRouteRequest, opts ...grpc.CallOption) (*OptimizedRoute, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OptimizedRoute)
	err := c.cc.Invoke(ctx, MapsService_OptimizeRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapsServiceClient) Track(ctx context.Context, in *TrackRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrackLocation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MapsService_ServiceDesc.Streams[0], MapsService_Track_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrackRequest, TrackLocation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MapsService_TrackClient = grpc.ServerStreamingClient[TrackLocation]

func (c *mapsServiceClient) GetStaticMap(ctx context.Context, in *StaticMapRequest, opts ...grpc.CallOption) (*StaticMap, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaticMap)
	err := c.cc.Invoke(ctx, MapsService_GetStaticMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapsServiceServer is the server API for MapsService service.
// All implementations must embed UnimplementedMapsServiceServer
// for forward compatibility.
type MapsServiceServer interface {
	GetDirections(context.Context, *GetDirectionsRequest) (*Route, error)
	SearchPlaces(context.Context, *SearchPlacesRequest) (*SearchPlacesResponse, error)
	Geocode(context.Context, *GeocodeRequest) (*GeocodeResponse, error)
	ReverseGeocode(context.Context, *ReverseGeocodeRequest) (*ReverseGeocodeResponse, error)
	DistanceMatrix(context.Context, *DistanceMatrixRequest) (*DistanceMatrixResponse, error)
	OptimizeRoute(context.Context, *OptimizeRouteRequest) (*OptimizedRoute, error)
	Track(*TrackRequest, grpc.ServerStreamingServer[TrackLocation]) error
	GetStaticMap(context.Context, *StaticMapRequest) (*StaticMap, error)
	mustEmbedUnimplementedMapsServiceServer()
}

// UnimplementedMapsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMapsServiceServer struct{}

func (UnimplementedMapsServiceServer) GetDirections(context.Context, *GetDirectionsRequest) (*Route, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDirections not implemented")
}
func (UnimplementedMapsServiceServer) SearchPlaces(context.Context, *SearchPlacesRequest) (*SearchPlacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchPlaces not implemented")
}
func (UnimplementedMapsServiceServer) Geocode(context.Context, *GeocodeRequest) (*GeocodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Geocode not implemented")
}
func (UnimplementedMapsServiceServer) ReverseGeocode(context.Context, *ReverseGeocodeRequest) (*ReverseGeocodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReverseGeocode not implemented")
}
func (UnimplementedMapsServiceServer) DistanceMatrix(context.Context, *DistanceMatrixRequest) (*DistanceMatrixResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistanceMatrix not implemented")
}
func (UnimplementedMapsServiceServer) OptimizeRoute(context.Context, *OptimizeRouteRequest) (*OptimizedRoute, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OptimizeRoute not implemented")
}
func (UnimplementedMapsServiceServer) Track(*TrackRequest, grpc.ServerStreamingServer[TrackLocation]) error {
	return status.Errorf(codes.Unimplemented, "method Track not implemented")
}
func (UnimplementedMapsServiceServer) GetStaticMap(context.Context, *StaticMapRequest) (*StaticMap, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStaticMap not implemented")
}
func (UnimplementedMapsServiceServer) mustEmbedUnimplementedMapsServiceServer() {}
func (UnimplementedMapsServiceServer) testEmbeddedByValue()                     {}

// UnsafeMapsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MapsServiceServer will
// result in compilation errors.
type UnsafeMapsServiceServer interface {
	mustEmbedUnimplementedMapsServiceServer()
}

func RegisterMapsServiceServer(s grpc.ServiceRegistrar, srv MapsServiceServer) {
	// If the following call pancis, it indicates UnimplementedMapsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MapsService_ServiceDesc, srv)
}

func _MapsService_GetDirections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDirectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServiceServer).GetDirections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapsService_GetDirections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServiceServer).GetDirections(ctx, req.(*GetDirectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapsService_SearchPlaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPlacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServiceServer).SearchPlaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapsService_SearchPlaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServiceServer).SearchPlaces(ctx, req.(*SearchPlacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapsService_Geocode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeocodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServiceServer).Geocode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapsService_Geocode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServiceServer).Geocode(ctx, req.(*GeocodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapsService_ReverseGeocode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseGeocodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServiceServer).ReverseGeocode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapsService_ReverseGeocode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServiceServer).ReverseGeocode(ctx, req.(*ReverseGeocodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapsService_DistanceMatrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistanceMatrixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServiceServer).DistanceMatrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapsService_DistanceMatrix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServiceServer).DistanceMatrix(ctx, req.(*DistanceMatrixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapsService_OptimizeRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizeRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServiceServer).OptimizeRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapsService_OptimizeRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServiceServer).OptimizeRoute(ctx, req.(*OptimizeRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapsService_Track_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TrackRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MapsServiceServer).Track(m, &grpc.GenericServerStream[TrackRequest, TrackLocation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MapsService_TrackServer = grpc.ServerStreamingServer[TrackLocation]

func _MapsService_GetStaticMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaticMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServiceServer).GetStaticMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapsService_GetStaticMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServiceServer).GetStaticMap(ctx, req.(*StaticMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MapsService_ServiceDesc is the grpc.ServiceDesc for MapsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MapsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "maps.MapsService",
	HandlerType: (*MapsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDirections",
			Handler:    _MapsService_GetDirections_Handler,
		},
		{
			MethodName: "SearchPlaces",
			Handler:    _MapsService_SearchPlaces_Handler,
		},
		{
			MethodName: "Geocode",
			Handler:    _MapsService_Geocode_Handler,
		},
		{
			MethodName: "ReverseGeocode",
			Handler:    _MapsService_ReverseGeocode_Handler,
		},
		{
			MethodName: "DistanceMatrix",
			Handler:    _MapsService_DistanceMatrix_Handler,
		},
		{
			MethodName: "OptimizeRoute",
			Handler:    _MapsService_OptimizeRoute_Handler,
		},
		{
			MethodName: "GetStaticMap",
			Handler:    _MapsService_GetStaticMap_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Track",
			Handler:       _MapsService_Track_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/maps.proto",
}
